language: python
python:
  - 3.6
before_install:
  - openssl aes-256-cbc -K $encrypted_e2b37024b6e1_key -iv $encrypted_e2b37024b6e1_iv -in .env.enc -out wisteria/.env -d
addons:
  chrome: stable
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - whereis google-chrome-stable
  - whereis chromedriver
  - pip install pipenv
  - pipenv sync --dev
before_script:
  - flake8 --max-line-length=100 --ignore=E203,W503 ./kbot
script:
  - py.test -v --capture=no --cov-config .coveragerc --cov=kbot .
after_success:
  - codecov
notifications:
  slack:
    secure: R0B6FLUM7xXnePVyC3WG31jAI8qrPL2SYYqg6WEuMsDML84o+GSuYxW4EHJwKU89aO+LgX6YgkO+tVvCxnMszqaanFkeCsNM5Ni/R13+Xor6wlLiE1ibFMRQMFEdrXqwxVlIGvKvxnsSfENZWA1ls/BGFgBhdqj0EIUEcyBt5I7D1ZEB1WfEL0fUD9uDXE52FM9ZOBl38xMghEMVcmZd6EIGXDYGuVU5lQkcPznYdiQSUdFXvxOBRbB9IjE7vr2+OZJ4SrJvcVW82J+hSRjZunLzP2LwiMsq7RNFrxrNjFIlbxZC/Z5Kgjjsy2W99uXvNXFThCHvWR2ChksuXmfy9iluu/zPLQN+2UDLF6LMUKdyleQU751CKeVQb5Dd1S7C0vbMSxQaJuCo35jwvGHnk641p/b/lFygsBvK7Lc4/AUK0Dp96H3pRaiABEo1enkOLRayT6GC/er20BPUeSbIdIDXVWiyYCTjVM2e3A5r2MCmuXNifXL3yR7jnZbN6SH8kmeQKqQqBDrBu/PYG6IZSPi9T6F2JBR/HCY53NXcqgHfL8yVG9kKhlxgdBHCUl882JIgqQLfNldejL0sNITpf/ifBfOKR+ZZ3QBhiQ1WmmsSdF/Use+A0DIUjBnAWxWL++/D9gsyTwTy7GUU4a+Z1xzHiZ+u5QS4070Tg+IRCIY=
